export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FALE = 'PRODUCT_LIST_FAIL'


export const PRODUCT_REQUEST_REQUEST = 'PRODUCT_REQUEST_REQUEST'
export const PRODUCT_REQUEST_SUCCESS = 'PRODUCT_REQUEST_SUCCESS'
export const PRODUCT_REQUEST_FALE = 'PRODUCT_REQUEST_FAIL'